import { useEffect,useRef,useState } from 'react';
import { UserRound, SlidersHorizontal, Plus, Trash2, LogOut, Shield } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { foods, CATEGORIES, type Category } from '@/lib/foods';
import { foodName,priceLabel,type Language } from '@/lib/i18n';
import { emptyProfile,validateProfile,type PoolProfile } from '@/lib/personal-pool';
import { type Account } from '@/hooks/use-account';
function GoogleLogin({account,language}:{account:Account;language:Language}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let live=true;if(ref.current)account.mountButton(ref.current,language).catch(()=>{if(live)account.setError(language==='vi'?'Không tải được Google. Đóng và mở lại để thử.':'Could not load Google. Close and reopen to retry.')});return()=>{live=false}},[account.mountButton,language]);
 return <div ref={ref}/>;
}
export function AccountPanel({account:a,language,disabled,variant='header'}:{account:Account;language:Language;disabled:boolean;variant?:'header'|'inventory'}){
 const vi=language==='vi';const [open,setOpen]=useState(false),[draft,setDraft]=useState<PoolProfile>(emptyProfile),[search,setSearch]=useState(''),[tab,setTab]=useState<'builtIn'|'custom'>('builtIn');
 const [editing,setEditing]=useState<string|null>(null),[name,setName]=useState(''),[price,setPrice]=useState('50'),[veg,setVeg]=useState(false),[catForm,setCatForm]=useState<Category>('mon-kho'),[notice,setNotice]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
 useEffect(()=>{setDraft(a.profile)},[a.profile]);
 const resetForm=()=>{setEditing(null);setName('');setPrice('50');setVeg(false);setCatForm('mon-kho')};
 function add(){
  try{const item={id:editing||crypto.randomUUID(),name:name.trim(),price:Number(price),veg,cat:catForm};const next=validateProfile({...draft,custom:editing?draft.custom.map(f=>f.id===editing?item:f):[...draft.custom,item]});setDraft(next);resetForm();setNotice('')}catch{setNotice(vi?'Tên 1–60 ký tự, giá 10–500 nghìn, tối đa 50 món.':'Name: 1–60 characters, price: 10–500k VND, up to 50 dishes.')}
 }
 const dirty=JSON.stringify(draft)!==JSON.stringify(a.profile);
 return <><button className={variant==='inventory'?'customize-food-button':'account-button'} disabled={disabled} onClick={()=>{setDraft(a.profile);setNotice('');setConfirmDelete(false);setOpen(true)}} aria-label={variant==='inventory'?(vi?'Tuỳ chỉnh món ăn':'Customize food'):(vi?'Pool của tôi':'My food pool')}>{variant==='inventory'?<><SlidersHorizontal size={16}/><span className="customize-full">{vi?'Tuỳ chỉnh món ăn':'Customize food'}</span><span className="customize-short">{vi?'Tuỳ chỉnh':'Customize'}</span></>:<><UserRound size={17}/><span>{a.user?(vi?'Pool của tôi':'My pool'):(vi?'Đăng nhập':'Sign in')}</span></>}</button>
 <Dialog open={open} onOpenChange={value=>{if(!a.pending)setOpen(value)}}><DialogContent className="account-dialog"><DialogTitle>{vi?'Pool của tôi':'My food pool'}</DialogTitle><DialogDescription>{a.user?(vi?'Chọn món bạn muốn quay trúng.':'Choose what goes into your case.'):(vi?'Thêm món bạn thích, bỏ món bạn không ăn.':'Add dishes you like, remove those you don’t eat.')}</DialogDescription>
 {!a.user?<div className="login-box"><GoogleLogin account={a} language={language}/><p>{vi?'Bạn vẫn có thể quay mà không cần đăng nhập.':'You can still spin without signing in.'}</p><a href="./privacy.html" target="_blank" rel="noreferrer">{vi?'Quyền riêng tư':'Privacy'}</a></div>:<>
 <div className="account-toolbar"><span>{a.user.name}</span>{a.user.admin&&<a href="#admin" onClick={()=>setOpen(false)}><Shield size={16}/> Admin</a>}<button disabled={a.pending} onClick={()=>{a.signOut();setOpen(false)}}><LogOut size={15}/>{vi?'Đăng xuất':'Sign out'}</button></div>
 <div className="pool-tabs"><button className={tab==='builtIn'?'selected':''} onClick={()=>setTab('builtIn')}>{vi?'Món có sẵn':'Catalog'} ({foods.length-draft.disabled.length})</button><button className={tab==='custom'?'selected':''} onClick={()=>setTab('custom')}>{vi?'Món tự thêm':'Custom'} ({draft.custom.length}/50)</button></div>
 <div className="pool-body"><fieldset disabled={a.pending}>
 {tab==='builtIn'?<><input className="pool-search" placeholder={vi?'Tìm món…':'Search dishes…'} aria-label={vi?'Tìm món':'Search dishes'} value={search} onChange={e=>setSearch(e.target.value)}/><div className="pool-list">{foods.filter(f=>foodName(f,language).toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(f=><label className="pool-row" key={f.image}><input type="checkbox" checked={!draft.disabled.includes(f.image)} onChange={e=>setDraft({...draft,disabled:e.target.checked?draft.disabled.filter(id=>id!==f.image):[...draft.disabled,f.image]})}/><span>{foodName(f,language)}{f.veg?' · 🌱':''}</span><small>{priceLabel(f.price,language)}</small></label>)}</div><button className="subtle-button" onClick={()=>setDraft({...draft,disabled:[]})}>{vi?'Bật lại tất cả món có sẵn':'Enable all catalog dishes'}</button></>:<>
 <div className="custom-form"><label>{vi?'Tên món':'Dish name'}<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label>{vi?'Giá (nghìn đồng)':'Price (thousand VND)'}<input type="number" min="10" max="500" step="1" inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>{vi?'Loại món':'Category'}<select value={catForm} onChange={e=>setCatForm(e.target.value as Category)}>{CATEGORIES.map(c=><option key={c.id} value={c.id}>{vi?c.vi:c.en}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={veg} onChange={e=>setVeg(e.target.checked)}/>{vi?'Món chay':'Vegetarian'}</label><button className="pool-primary" onClick={add}><Plus size={16}/>{editing?(vi?'Cập nhật':'Update'):(vi?'Thêm món':'Add dish')}</button>{editing&&<button onClick={resetForm}>{vi?'Huỷ sửa':'Cancel edit'}</button>}</div>
 <div className="pool-list">{draft.custom.length===0&&<p>{vi?'Thêm quán cơm quen hoặc món tủ của bạn.':'Add your favorite lunch dish.'}</p>}{draft.custom.map(f=>{const catLabel=CATEGORIES.find(c=>c.id===f.cat);return <div className="pool-row" key={f.id}><button onClick={()=>{setEditing(f.id);setName(f.name);setPrice(String(f.price));setVeg(f.veg);setCatForm(f.cat)}}>{f.name}{f.veg?' · 🌱':''}{catLabel?` · ${vi?catLabel.vi:catLabel.en}`:''}</button><small>{priceLabel(f.price,language)}</small><button aria-label={`${vi?'Xóa':'Remove'} ${f.name}`} onClick={()=>{setDraft({...draft,custom:draft.custom.filter(item=>item.id!==f.id)});if(editing===f.id)resetForm()}}><Trash2 size={15}/></button></div>})}</div></>}
 </fieldset></div>
 <div className="pool-save"><small>{foods.length-draft.disabled.length+draft.custom.length} {vi?'món trong hòm':'dishes in case'} · {dirty?(vi?'Chưa lưu':'Unsaved'):(vi?'Đã đồng bộ':'Synced')}</small><button className="pool-primary" disabled={a.pending||!dirty} onClick={async()=>{try{validateProfile(draft)}catch{setNotice(vi?'Giữ lại ít nhất một món.':'Keep at least one dish.');return}if(await a.save(draft)){setNotice(vi?'Đã lưu pool.':'Pool saved.')}}}><SlidersHorizontal size={16}/>{a.pending?'…':vi?'Lưu pool':'Save pool'}</button></div>
 <div className="account-bottom"><button disabled={a.pending} onClick={async()=>{const p=await a.reload();if(p)setDraft(p)}}>{vi?'Tải lại từ tài khoản':'Reload from account'}</button><button disabled={a.pending} onClick={()=>setConfirmDelete(!confirmDelete)}>{vi?'Xóa dữ liệu cá nhân':'Delete my data'}</button></div>{confirmDelete&&<div className="delete-confirm"><p>{vi?'Xóa vĩnh viễn pool đã lưu và đăng xuất?':'Permanently delete your saved pool and sign out?'}</p><button disabled={a.pending} onClick={async()=>{if(await a.remove())setOpen(false)}}>{vi?'Xác nhận xóa':'Confirm deletion'}</button></div>}
 </>}
 {(a.error||notice)&&<p className="account-message" role="status">{a.error||notice}</p>}
 </DialogContent></Dialog></>;
}
export function AdminPanel({account:a,language,globalSpins}:{account:Account;language:Language;globalSpins:number|null}){
 const vi=language==='vi';const [data,setData]=useState<Record<string,number|string>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const refresh=async()=>{setLoading(true);setError('');try{setData(await a.request<Record<string,number|string>>('/admin/summary'))}catch(e){setError(e instanceof Error?e.message:'Failed')}finally{setLoading(false)}};
 useEffect(()=>{if(a.user?.admin)void refresh()},[a.user?.sub]);
 return <section className="admin-panel"><a href="#">← {vi?'Quay hòm':'Back to cases'}</a><h1>Admin</h1>{!a.user?<p>{vi?'Đăng nhập tài khoản quản trị ở góc trên.':'Sign in with your administrator account above.'}</p>:!a.user.admin?<p>{vi?'Tài khoản không có quyền quản trị.':'This account does not have administrator access.'}</p>:<><button className="pool-primary" disabled={loading} onClick={()=>void refresh()}>{loading?'…':vi?'Cập nhật':'Refresh'}</button>{error&&<p role="alert">{error}</p>}{data&&<><p>{vi?'Kiểm tra lúc':'Checked at'}: {new Date(data.checkedAt).toLocaleString(vi?'vi-VN':'en-US')}</p><div className="admin-stats">{[[vi?'Lượt quay ước tính':'Estimated spins',Math.max(Number(data.count),globalSpins??0)],[vi?'Pool đã lưu':'Saved profiles',data.profiles],[vi?'Món tự thêm':'Custom dishes',data.customFoods],[vi?'Pool cập nhật trong 24h':'Profiles updated in 24h',data.updatedToday],['D1 latency (ms)',data.databaseMs]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value).toLocaleString(vi?'vi-VN':'en-US')}</strong></div>)}</div></>}<p>{vi?'Số pool đã lưu không phải tổng người đăng nhập. Traffic, CPU, lỗi và chi phí xem trong Cloudflare.':'Saved profiles are not total sign-ins. View traffic, CPU, errors and billing in Cloudflare.'}</p><a href="https://dash.cloudflare.com/" target="_blank" rel="noreferrer">Cloudflare Dashboard ↗</a></>}</section>;
}
